// Enterprise-grade ERP Mock Data for WFX AI-Native ERP Platform

export const kpiData = {
  totalFinishedGoods: 4520,
  totalSuppliers: 48,
  totalBuyers: 32,
  totalOrders: 1280,
  totalRevenue: 2458400, // $2.45M
  changes: {
    finishedGoods: "+12.4% vs last month",
    suppliers: "+4.2% vs last month",
    buyers: "+8.1% vs last month",
    orders: "+18.6% vs last month",
    revenue: "+22.3% vs last quarter",
  }
};

export const revenueTrend = [
  { month: 'Jan', Revenue: 185000, Profit: 55000, Orders: 95 },
  { month: 'Feb', Revenue: 210000, Profit: 68000, Orders: 110 },
  { month: 'Mar', Revenue: 245000, Profit: 78000, Orders: 130 },
  { month: 'Apr', Revenue: 220000, Profit: 70000, Orders: 115 },
  { month: 'May', Revenue: 290000, Profit: 95000, Orders: 145 },
  { month: 'Jun', Revenue: 340000, Profit: 112000, Orders: 170 },
  { month: 'Jul', Revenue: 380000, Profit: 128000, Orders: 195 },
  { month: 'Aug', Revenue: 360000, Profit: 118000, Orders: 180 },
  { month: 'Sep', Revenue: 410000, Profit: 139000, Orders: 210 },
  { month: 'Oct', Revenue: 430000, Profit: 146000, Orders: 220 },
  { month: 'Nov', Revenue: 490000, Profit: 168000, Orders: 250 },
  { month: 'Dec', Revenue: 560000, Profit: 198000, Orders: 290 },
];

export const supplierPerformance = [
  { id: 1, name: 'Apex Apparel Corp', score: 94, onTime: 96, quality: 95, leadTime: '12 days' },
  { id: 2, name: 'Zenith Textiles', score: 88, onTime: 90, quality: 89, leadTime: '18 days' },
  { id: 3, name: 'Global Weaves', score: 91, onTime: 92, quality: 93, leadTime: '15 days' },
  { id: 4, name: 'Himalayan Knits', score: 85, onTime: 82, quality: 88, leadTime: '22 days' },
  { id: 5, name: 'Pacific Garments', score: 96, onTime: 98, quality: 97, leadTime: '10 days' },
];

export const productCategories = [
  { name: 'Knits', value: 1680, color: '#6366f1' },
  { name: 'Wovens', value: 1120, color: '#3b82f6' },
  { name: 'Denim', value: 850, color: '#10b981' },
  { name: 'Outerwear', value: 520, color: '#f59e0b' },
  { name: 'Activewear', value: 350, color: '#ec4899' },
];

export const recentActivity = [
  { id: 1, type: 'order', title: 'New order placed', detail: 'Buyer Zara placed order WFX-ORD-9844 for 1,200 units.', time: '10 mins ago', status: 'pending' },
  { id: 2, type: 'shipping', title: 'Shipment dispatched', detail: 'Pacific Garments shipped 800 Denim Jackets (WFX-DJ-02).', time: '2 hours ago', status: 'success' },
  { id: 3, type: 'supplier', title: 'Quality check completed', detail: 'Apex Apparel Corp Batch #49 passed QC with 99.2% score.', time: '5 hours ago', status: 'success' },
  { id: 4, type: 'buyer', title: 'Payment received', detail: 'Received $48,500 from UNIQLO for Spring collection delivery.', time: '1 day ago', status: 'info' },
  { id: 5, type: 'product', title: 'New design uploaded', detail: 'Designer uploaded tech pack for "Oversized Merino Sweater".', time: '2 days ago', status: 'warning' },
];

export const products = [
  {
    id: 1,
    styleNumber: 'WFX-KT-001',
    styleName: 'Minimalist Cotton Tee',
    category: 'Knits',
    fabric: '100% Organic Cotton',
    gsm: 180,
    supplier: 'Apex Apparel Corp',
    buyer: 'UNIQLO',
    print: 'Solid',
    color: 'Off-White',
    season: 'Spring/Summer 2026',
    sellingPrice: 12.50,
    stockQuantity: 1500,
    imageUrl: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80',
    similarityScore: 98.4
  },
  {
    id: 2,
    styleNumber: 'WFX-HD-002',
    styleName: 'Cozy French Terry Hoodie',
    category: 'Knits',
    fabric: '80% Cotton, 20% Polyester French Terry',
    gsm: 320,
    supplier: 'Zenith Textiles',
    buyer: 'H&M',
    print: 'Solid',
    color: 'Midnight Blue',
    season: 'Fall/Winter 2026',
    sellingPrice: 24.50,
    stockQuantity: 850,
    imageUrl: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=600&q=80',
    similarityScore: 95.2
  },
  {
    id: 3,
    styleNumber: 'WFX-DJ-003',
    styleName: 'Classic Selvedge Denim Jacket',
    category: 'Denim',
    fabric: '100% Selvedge Denim Cotton',
    gsm: 420,
    supplier: 'Global Weaves',
    buyer: 'Zara',
    print: 'Solid',
    color: 'Midnight Blue',
    season: 'Fall/Winter 2026',
    sellingPrice: 48.00,
    stockQuantity: 420,
    imageUrl: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=600&q=80',
    similarityScore: 91.8
  },
  {
    id: 4,
    styleNumber: 'WFX-LJ-004',
    styleName: 'Premium Leather Biker Jacket',
    category: 'Outerwear',
    fabric: '100% Full-Grain Cow Leather',
    gsm: 650,
    supplier: 'Pacific Garments',
    buyer: 'Nordstrom',
    print: 'Solid',
    color: 'Charcoal',
    season: 'Fall/Winter 2026',
    sellingPrice: 125.00,
    stockQuantity: 180,
    imageUrl: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=600&q=80',
    similarityScore: 88.5
  },
  {
    id: 5,
    styleNumber: 'WFX-JG-005',
    styleName: 'Urban Fleece Joggers',
    category: 'Activewear',
    fabric: '70% Cotton, 30% Polyester Fleece',
    gsm: 280,
    supplier: 'Himalayan Knits',
    buyer: 'ASOS',
    print: 'Solid',
    color: 'Heather Grey',
    season: 'Spring/Summer 2026',
    sellingPrice: 18.50,
    stockQuantity: 950,
    imageUrl: 'https://images.unsplash.com/photo-1552642986-ccb41e7059e7?auto=format&fit=crop&w=600&q=80',
    similarityScore: 86.1
  },
  {
    id: 6,
    styleNumber: 'WFX-DR-006',
    styleName: 'Summer Linen Midi Dress',
    category: 'Wovens',
    fabric: '100% Pure Flax Linen',
    gsm: 150,
    supplier: 'Apex Apparel Corp',
    buyer: 'Zara',
    print: 'Solid',
    color: 'Off-White',
    season: 'Spring/Summer 2026',
    sellingPrice: 32.00,
    stockQuantity: 620,
    imageUrl: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=600&q=80',
    similarityScore: 84.4
  },
  {
    id: 7,
    styleNumber: 'WFX-SH-007',
    styleName: 'Oxford Button-Down Shirt',
    category: 'Wovens',
    fabric: '100% Combed Cotton Oxford',
    gsm: 160,
    supplier: 'Global Weaves',
    buyer: 'UNIQLO',
    print: 'Solid',
    color: 'Off-White',
    season: 'Spring/Summer 2026',
    sellingPrice: 16.50,
    stockQuantity: 1100,
    imageUrl: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80',
    similarityScore: 81.3
  },
  {
    id: 8,
    styleNumber: 'WFX-SW-008',
    styleName: 'Cable Knit Merino Sweater',
    category: 'Knits',
    fabric: '100% Merino Wool',
    gsm: 400,
    supplier: 'Himalayan Knits',
    buyer: 'Nordstrom',
    print: 'Solid',
    color: 'Olive Green',
    season: 'Fall/Winter 2026',
    sellingPrice: 58.00,
    stockQuantity: 340,
    imageUrl: 'https://images.unsplash.com/photo-1574164904299-3a102b110380?auto=format&fit=crop&w=600&q=80',
    similarityScore: 80.9
  },
  {
    id: 9,
    styleNumber: 'WFX-PF-009',
    styleName: 'Ultralight Puffer Jacket',
    category: 'Outerwear',
    fabric: '100% Recycled Nylon Ripstop / Duck Down',
    gsm: 80,
    supplier: 'Pacific Garments',
    buyer: 'UNIQLO',
    print: 'Solid',
    color: 'Midnight Blue',
    season: 'Fall/Winter 2026',
    sellingPrice: 75.00,
    stockQuantity: 780,
    imageUrl: 'https://images.unsplash.com/photo-1544923246-77307dd654cb?auto=format&fit=crop&w=600&q=80',
    similarityScore: 78.4
  },
  {
    id: 10,
    styleNumber: 'WFX-CP-010',
    styleName: 'Ripstop Cargo Pants',
    category: 'Wovens',
    fabric: 'Nylon/Cotton Blend Ripstop',
    gsm: 220,
    supplier: 'Zenith Textiles',
    buyer: 'ASOS',
    print: 'Solid',
    color: 'Olive Green',
    season: 'Spring/Summer 2026',
    sellingPrice: 22.00,
    stockQuantity: 980,
    imageUrl: 'https://images.unsplash.com/photo-1517423568366-8b83523034fd?auto=format&fit=crop&w=600&q=80',
    similarityScore: 75.6
  },
  {
    id: 11,
    styleNumber: 'WFX-KT-011',
    styleName: 'Striped Cotton Breton Tee',
    category: 'Knits',
    fabric: '100% Interlock Cotton',
    gsm: 210,
    supplier: 'Apex Apparel Corp',
    buyer: 'H&M',
    print: 'Striped',
    color: 'Off-White',
    season: 'Spring/Summer 2026',
    sellingPrice: 14.00,
    stockQuantity: 1200,
    imageUrl: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80',
    similarityScore: 72.1
  },
  {
    id: 12,
    styleNumber: 'WFX-HD-012',
    styleName: 'Tie-Dye Oversized Hoodie',
    category: 'Knits',
    fabric: '100% Terry Cotton',
    gsm: 340,
    supplier: 'Zenith Textiles',
    buyer: 'Zara',
    print: 'Tie-Dye',
    color: 'Heather Grey',
    season: 'Pre-Fall 2026',
    sellingPrice: 28.00,
    stockQuantity: 450,
    imageUrl: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=600&q=80',
    similarityScore: 70.3
  },
  {
    id: 13,
    styleNumber: 'WFX-DJ-013',
    styleName: 'Distressed Denim Jacket',
    category: 'Denim',
    fabric: 'Cotton Elastane Blend Denim',
    gsm: 400,
    supplier: 'Global Weaves',
    buyer: 'ASOS',
    print: 'Solid',
    color: 'Midnight Blue',
    season: 'Spring/Summer 2026',
    sellingPrice: 42.50,
    stockQuantity: 550,
    imageUrl: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=600&q=80',
    similarityScore: 68.9
  },
  {
    id: 14,
    styleNumber: 'WFX-LJ-014',
    styleName: 'Suede Bomber Jacket',
    category: 'Outerwear',
    fabric: '100% Goat Suede Leather',
    gsm: 580,
    supplier: 'Pacific Garments',
    buyer: 'Nordstrom',
    print: 'Solid',
    color: 'Charcoal',
    season: 'Fall/Winter 2026',
    sellingPrice: 110.00,
    stockQuantity: 210,
    imageUrl: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=600&q=80',
    similarityScore: 65.4
  },
  {
    id: 15,
    styleNumber: 'WFX-JG-015',
    styleName: 'Performance Track Pants',
    category: 'Activewear',
    fabric: 'Poly-Spandex Stretch Blend',
    gsm: 240,
    supplier: 'Himalayan Knits',
    buyer: 'UNIQLO',
    print: 'Solid',
    color: 'Charcoal',
    season: 'Spring/Summer 2026',
    sellingPrice: 20.00,
    stockQuantity: 880,
    imageUrl: 'https://images.unsplash.com/photo-1552642986-ccb41e7059e7?auto=format&fit=crop&w=600&q=80',
    similarityScore: 62.1
  },
  {
    id: 16,
    styleNumber: 'WFX-DR-016',
    styleName: 'Floral Print Georgette Dress',
    category: 'Wovens',
    fabric: '100% Viscose Crepe',
    gsm: 130,
    supplier: 'Apex Apparel Corp',
    buyer: 'H&M',
    print: 'Graphic',
    color: 'Burgundy',
    season: 'Spring/Summer 2026',
    sellingPrice: 35.00,
    stockQuantity: 480,
    imageUrl: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=600&q=80',
    similarityScore: 59.8
  },
  {
    id: 17,
    styleNumber: 'WFX-SH-017',
    styleName: 'Linen Vacation Collar Shirt',
    category: 'Wovens',
    fabric: '55% Linen, 45% Cotton Blend',
    gsm: 140,
    supplier: 'Global Weaves',
    buyer: 'Zara',
    print: 'Solid',
    color: 'Off-White',
    season: 'Spring/Summer 2026',
    sellingPrice: 19.50,
    stockQuantity: 740,
    imageUrl: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80',
    similarityScore: 55.4
  },
  {
    id: 18,
    styleNumber: 'WFX-SW-018',
    styleName: 'Mock Neck Knit Sweater',
    category: 'Knits',
    fabric: '80% Lambswool, 20% Nylon',
    gsm: 380,
    supplier: 'Himalayan Knits',
    buyer: 'Zara',
    print: 'Solid',
    color: 'Charcoal',
    season: 'Fall/Winter 2026',
    sellingPrice: 49.00,
    stockQuantity: 410,
    imageUrl: 'https://images.unsplash.com/photo-1574164904299-3a102b110380?auto=format&fit=crop&w=600&q=80',
    similarityScore: 52.8
  },
  {
    id: 19,
    styleNumber: 'WFX-PF-019',
    styleName: 'Windbreaker Hooded Jacket',
    category: 'Outerwear',
    fabric: '100% Polyester DWR Coated',
    gsm: 110,
    supplier: 'Pacific Garments',
    buyer: 'ASOS',
    print: 'Solid',
    color: 'Midnight Blue',
    season: 'Spring/Summer 2026',
    sellingPrice: 38.00,
    stockQuantity: 620,
    imageUrl: 'https://images.unsplash.com/photo-1544923246-77307dd654cb?auto=format&fit=crop&w=600&q=80',
    similarityScore: 48.7
  },
  {
    id: 20,
    styleNumber: 'WFX-CP-020',
    styleName: 'Checked Flannel Joggers',
    category: 'Activewear',
    fabric: '100% Cotton Flannel Brushed',
    gsm: 200,
    supplier: 'Zenith Textiles',
    buyer: 'Nordstrom',
    print: 'Checked',
    color: 'Burgundy',
    season: 'Fall/Winter 2026',
    sellingPrice: 25.00,
    stockQuantity: 520,
    imageUrl: 'https://images.unsplash.com/photo-1517423568366-8b83523034fd?auto=format&fit=crop&w=600&q=80',
    similarityScore: 45.2
  }
];

export const nlQueries = [
  {
    query: 'Show me total revenue by supplier',
    sql: `SELECT supplier, SUM(selling_price * stock_quantity) AS total_revenue 
FROM products 
GROUP BY supplier 
ORDER BY total_revenue DESC;`,
    headers: ['Supplier', 'Total Revenue'],
    rows: [
      ['Pacific Garments', '$135,160.00'],
      ['Apex Apparel Corp', '$45,210.00'],
      ['Global Weaves', '$43,365.00'],
      ['Himalayan Knits', '$39,510.00'],
      ['Zenith Textiles', '$32,605.00'],
    ],
    aiResponse: 'Pacific Garments leads in potential revenue contribution with $135,160.00 due to premium jackets, followed closely by Apex Apparel and Global Weaves.'
  },
  {
    query: 'Find garments with fabric containing Cotton and price under 20',
    sql: `SELECT style_number, style_name, fabric, selling_price, stock_quantity 
FROM products 
WHERE fabric LIKE '%Cotton%' AND selling_price < 20.00;`,
    headers: ['Style No', 'Style Name', 'Fabric', 'Price', 'Stock'],
    rows: [
      ['WFX-KT-001', 'Minimalist Cotton Tee', '100% Organic Cotton', '$12.50', '1,500'],
      ['WFX-JG-005', 'Urban Fleece Joggers', '70% Cotton Fleece', '$18.50', '950'],
      ['WFX-SH-007', 'Oxford Button-Down', '100% Oxford Cotton', '$16.50', '1,100'],
      ['WFX-KT-011', 'Striped Breton Tee', '100% Interlock Cotton', '$14.00', '1,200'],
      ['WFX-SH-017', 'Linen Vacation Shirt', '55% Linen, 45% Cotton', '$19.50', '740'],
    ],
    aiResponse: 'Found 5 cotton-based items retailing below $20.00. The "Minimalist Cotton Tee" (WFX-KT-001) has the largest inventory size at 1,500 units.'
  },
  {
    query: 'List top buyers by ordered stock',
    sql: `SELECT buyer, SUM(stock_quantity) AS total_units_ordered 
FROM products 
GROUP BY buyer 
ORDER BY total_units_ordered DESC;`,
    headers: ['Buyer Brand', 'Total Units Allocated'],
    rows: [
      ['UNIQLO', '4,480 units'],
      ['Zara', '3,440 units'],
      ['H&M', '2,530 units'],
      ['ASOS', '2,830 units'],
      ['Nordstrom', '1,250 units'],
    ],
    aiResponse: 'UNIQLO is your largest partner by volume, with 4,480 units currently allocated across various styles, followed by Zara with 3,440 units.'
  },
  {
    query: 'What is the average price of heavy garments (GSM > 300)?',
    sql: `SELECT AVG(selling_price) AS average_price 
FROM products 
WHERE gsm > 300;`,
    headers: ['garment_type', 'avg_selling_price', 'count'],
    rows: [
      ['Heavyweight (>300 GSM)', '$64.88', '6 styles'],
    ],
    aiResponse: 'Heavyweight fabrics (GSM > 300) have an average retail price of $64.88 across 6 unique styles, largely driven by leather and outerwear collections.'
  }
];
